### ISSUE TITLE
AM/PM display is settable on 24h clock

### ISSUE THREAD

**Issue by silverclaw** [slushpupie/DeskClock#12]
The option to display AM/PM should be disabled when the 24h clock is selected (this is already done for the "leading 0" option).

HTC One S unrooted (Android 4.0)

**Comment by slushpupie** [comment]
It is settable, and though odd, is a perfectly valid thing to do.

**Comment by Wirat12** [comment]
> The option to display AM/PM should be disabled when the 24h clock is selected (this is already done for the "leading 0" option).
> 
> HTC One S unrooted (Android 4.0)
>
