### ISSUE TITLE
Roboto Font

### ISSUE THREAD

**Issue by Bandolica** [slushpupie/DeskClock#9]
Please add "Robot Thin" and "Roboto Light" fonts to the font settings. Can easily be downloaded for free on the official Android design site: http://developer.android.com/design/style/typography.html

Thanks

**Comment by slushpupie** [comment]
Its not quite as easy as just adding a new font.  The combination of dynamic widths (unless its a monospaced font) and kerning makes for some ugly display of fonts that are normally beautiful.  The Robot fonts are not monospaced, which means I cannot use them as-is.  Ill look into options, however.

**Comment by Bandolica** [comment]
Cool, sounds good. Thanks.

**Comment by Bandolica** [comment]
Just to let you, I don't know if it makes an implementation any easier: "Roboto Thin" actually is a monospaced font.
